apiVersion: apps/v1
kind: Deployment
metadata:
  name: mhc-front
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  minReadySeconds: 15 
  selector:
    matchLabels:
      app: mhc-front
  template:
    metadata:
      labels:
        app: mhc-front
    spec:
      containers:
      - name: mhc-front
        image: __ACR__
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        #env:
        #- name: REDIS
         # value: "mhc-back"
 
---
 
apiVersion: v1
kind: Service
metadata:
  name: mhc-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mhc-front

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mhc-back
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  minReadySeconds: 15 
  selector:
    matchLabels:
      app: mhc-back
  template:
    metadata:
      labels:
        app: mhc-back
    spec:
      containers:
      - name: mhc-back
        image: __ACR__
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        #env:
        #- name: REDIS
         # value: "mhc-back"
 
---
 
apiVersion: v1
kind: Service
metadata:
  name: mhc-back
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mhc-back

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-fanout-example
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: mhc-back
          servicePort: 4200
      - path: /bar
        backend:
          serviceName: mhc-front
          servicePort: 8080


